### ISSUE TITLE
Poor navigations on mobile

### ISSUE THREAD

**Issue by AumyF** [drizzle-team/drizzle-orm-docs#144]
Nextra's sidebar, which contains the index of documents, is not shown in mobile view (`width<768px`) and readers cannot even open other pages.

I suggest using the native `navbar` provided by Nextra docs theme.

![](https://github.com/drizzle-team/drizzle-orm-docs/assets/46275902/bc4c6cc1-9e4b-411c-a191-d1ed947b17e4)

![image](https://github.com/drizzle-team/drizzle-orm-docs/assets/46275902/0a5ec915-de7a-4206-9e13-b9deff0c5a15)

**Comment by AlexBlokh** [comment]
hey @AumyF 
we're not aiming to spend much time on mobile experience for docs, meant to be used from PC
