### ISSUE TITLE
Landing page show negative tweets

### ISSUE THREAD

**Issue by psycho-baller** [drizzle-team/drizzle-orm-docs#177]
![image](https://github.com/drizzle-team/drizzle-orm-docs/assets/81759594/70d2e7b6-5fd4-4b93-9776-9adb161c1559)

I'm so confused... why is there only [negative tweets](https://orm.drizzle.team/#pricing) in [this file](https://github.com/drizzle-team/drizzle-orm-docs/blob/master/components/pages/LandingPage/LandingComponents/Twits/Comments.ts) and it seems to have been like that for months. I can't image this being unnoticed for that long so there must be a reason you guys have these tweets. Whatever it is, it was going to drive me away from using drizzle and switch to Prisma

**Comment by matthewvolk** [comment]
FWIW, I thought showcasing those negative tweets was so funny that I converted _from_ Prisma _to_ Drizzle

**Comment by imMatheus** [comment]
I think this is just satire form their part, and ment to be like that 😁

**Comment by Sn-Kinos** [comment]
- https://github.com/drizzle-team/drizzle-orm-docs/issues/202 🤣🤣🤣

**Comment by psycho-baller** [comment]
nvm then😂
