### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by MoSattler** [drizzle-team/drizzle-orm-docs#178]
Many, many links are not working in the docs. It seems to be the ones that are relative. Som examples:

- https://github.com/drizzle-team/drizzle-orm-docs/blob/main/src/content/documentation/docs/column-types/sqlite.mdx#L12
- https://github.com/drizzle-team/drizzle-orm-docs/blob/main/src/content/documentation/docs/column-types/mysql.mdx#L7
- https://github.com/drizzle-team/drizzle-orm-docs/blob/main/src/content/documentation/kit-docs/faq.mdx#L14

**Comment by AlexBlokh** [comment]
fixed
