### ISSUE TITLE
Landing page... what's going on with the Tweets?

### ISSUE THREAD

**Issue by OliverCordingl1** [drizzle-team/drizzle-orm-docs#202]
I have to be honest, I had a bit of a chuckle seeing this - but surely this isn't intended, right?

<img width="1125" alt="Screenshot 2024-01-06 at 12 53 20" src="https://github.com/drizzle-team/drizzle-orm-docs/assets/19516518/effda210-3fc6-4ce7-80e5-bba03836e12c">

(FYI, this is hardcoded [here](https://github.com/drizzle-team/drizzle-orm-docs/blame/5c113a5a732ca106dda5ca7dd51995e35eea87e1/src/components/LandingPage/Twits/Comments.ts), I'm guessing this was meant to be temporary?)

**Comment by AlexBlokh** [comment]
those are intended and all are real quotes from real people, but thanks!
