### ISSUE TITLE
Iterator for MySQL

### ISSUE THREAD

**Issue by rizen** [drizzle-team/drizzle-orm-docs#232]
Back in 0.24.0 I paid for a feature called iterator to be added to Drizzle. It's still in the code, but the documentation for it went away when the newer docs were added to Drizzle. 

The feature helps when you need to pull back hundreds of thousands or millions of lines of code. It's a shame that the feature is still there but that there are no docs explaining how to use it. Bring back the docs!

**Comment by rizen** [comment]
As an aside, if someone has access to the old docs and would link them here for me, I'd be happy to reformat them and patch them into the new docs as a pull request. I just don't know where to find the old docs.

**Comment by vlad-stohnii** [comment]
Sorry about that, we lost this section before we moved to Astro. We've returned this section, you can find it here: https://orm.drizzle.team/docs/select#iterator
