### ISSUE TITLE
[REQUEST] We can help improve dx with documentation (add instructions for using drizzle to popular technologies)

### ISSUE THREAD

**Issue by wrknbuycnsmndie** [drizzle-team/drizzle-orm-docs#243]
Hello! my proposal is due to the fact that many popular technologies like prisma, nest js and others have instructions on how to set up work with this or that technology for faster development. Can this be applied to drizzle? I think more people would use it if there was a clear guide to setting it up.

Thanks for reading, I'd love to hear your feedback.

**Comment by AlexBlokh** [comment]
we're actively building Learn section for that currently
