### ISSUE TITLE
Function missing id param in docs

### ISSUE THREAD

**Issue by matheuschimelli** [drizzle-team/drizzle-orm-docs#278]
In the following page [Drizzle nextjs neon example](https://orm.drizzle.team/learn/tutorials/drizzle-nextjs-neon), there is two example functions:

The first one shows how to add a todo:
```js
import db from "@/db/drizzle";
import { todo } from "@/db/schema";
export const addTodo = async (id: number, text: string) => {
  await db.insert(todo).values({
    id: id,
    text: text,
  });
};
```
But at the end of the docs in the "Establish server-side functions", the function is missing the id param:
```js
export const addTodo = async (text: string) => {
  await db.insert(todo).values({
    text: text,
  });
  revalidatePath("/");
};
```

I created a pull request to fix it: #277

**Comment by realmikesolo** [comment]
PR was merged, so I will close the issue
