### ISSUE TITLE
Should "Due to" be "According to"

### ISSUE THREAD

**Issue by iqrow** [drizzle-team/drizzle-orm-docs#3]
I see a lot of docs entries say "Due to their official website...", but I believe this should be "According to their official website". Would you be open to a PR to change that?

**Comment by AndriiSherman** [comment]
Sure, feel free to add a PR for this fix

**Comment by iqrow** [comment]
Looks like @kyrylolvov got to it first :clap: :bow: 
https://github.com/drizzle-team/drizzle-orm-docs/pull/9
