### ISSUE TITLE
Typo in drizzle-with-turso tutorial

### ISSUE THREAD

**Issue by harshmangalam** [drizzle-team/drizzle-orm-docs#343]
In `Basic file structure` section there is typo in file name `db.ts` it should be `index.ts`.

https://orm.drizzle.team/learn/tutorials/drizzle-with-turso

**Comment by harshmangalam** [comment]
https://github.com/drizzle-team/drizzle-orm-docs/pull/344

**Comment by realmikesolo** [comment]
Closed due to merged PR
