### ISSUE TITLE
Drizzle docs show scam/spam?

### ISSUE THREAD

**Issue by Nick-Mazuk** [drizzle-team/drizzle-orm-docs#391]
When I view the Drizzle documentation, I see the following website:

<img width="1280" alt="Screenshot 2024-09-08 at 8 42 26 AM" src="https://github.com/user-attachments/assets/930d4808-fdda-4239-b18a-a10fe19dfc5f">

I can replicate on both Safari and Arc, using incognito/private and normal windows for both. Seems flakey—about ~20% of the time I see the actual documentation website. I've double-checked the URL matches the URL in this repo.

<img width="336" alt="Screenshot 2024-09-08 at 8 45 11 AM" src="https://github.com/user-attachments/assets/18217124-ead5-45e6-a1ba-e350c30a65fd">

**Comment by HappyEmu** [comment]
I see the same. Funny, I just wanted to take a look at Drizzle for the weekend and right when I want to read the docs, this happens 🙁

**Comment by whilestevego** [comment]
They're on it https://github.com/drizzle-team/drizzle-orm/issues/2929

**Comment by Nick-Mazuk** [comment]
Closing this issue in favor of https://github.com/drizzle-team/drizzle-orm/issues/2929 and because it seems like the site is back up.
