### ISSUE TITLE
Wrong package for node-postgres guide

### ISSUE THREAD

**Issue by sparanoid** [drizzle-team/drizzle-orm-docs#401]
https://orm.drizzle.team/docs/get-started-postgresql

The postgres guide installs the wrong package [`node-postgres`](https://www.npmjs.com/package/node-postgres) which should be [`pg`](https://www.npmjs.com/package/pg): https://node-postgres.com/

**Comment by mbtools** [comment]
Looks correct to me now

![image](https://github.com/user-attachments/assets/1d832e13-23b4-452a-a44e-86c4a811b757)
