### ISSUE TITLE
Navbar documentation text appears twice on mobile

### ISSUE THREAD

**Issue by JoltCode** [drizzle-team/drizzle-orm-docs#47]
On mobile, the navigation bar shows "Documentation" twice (one is for Drizzle ORM, and one is for Drizzle Kit).

**Comment by JoltCode** [comment]
![Screenshot_2023-06-12-17-36-45-13_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/drizzle-team/drizzle-orm-docs/assets/46378904/054386cc-921c-4c0b-bb82-8871e41aecc8)

**Comment by ScriptRaccoon** [comment]
Yes, same here.
![menudouble](https://github.com/drizzle-team/drizzle-orm-docs/assets/54458975/d8555fda-b150-497e-b09f-084ca02bd7b9)

**Comment by JoltCode** [comment]
Any updates on this? :sweat_smile:

**Comment by Rajdeep-Das** [comment]
![display_hidden](https://github.com/drizzle-team/drizzle-orm-docs/assets/22764172/92ceb184-d964-42f3-91b2-d6e0cd627918)

Nextra display is hidden not working on mobile, I guess.

**Comment by AlexBlokh** [comment]
yes, we're implementing v2 of the docs with custom header, won't be an issue
